default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: dev
  password:  <%= ENV['DATABASE_PASSWORD'] || 'pass1234' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: online_auction_system

test:
  <<: *default
  database: online_auction_system_test

production:
  <<: *default
  database: online_auction_system_production
